name: Run Tests on Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup PNPM
        id: setup-pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v5

      - name: Install Dependencies
        id: install
        run: pnpm install

      - name: Run Tests
        id: vitest-test
        run: pnpm run test
